# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d1437faaf4db3e7b724dd156530f77c00315e6f6c4eb978645123dbb42a51b4706aa768dcc672ca085b1b055ecb6ea805aa005d4d31232bee34814a0d55dd1e

test:
  secret_key_base: 1bcdc0e717572ac7e98fc5916e155fdbfaa8f7f12f11b623a75a66fa95a9a5bec313a0d31e8e21666324f94fac329f21d65107eee7d39f0e3ad63c7bdf3b9c5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
